# Grafana Datasources Provisioning
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://gapanalyzer-prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      prometheusType: Prometheus
      prometheusVersion: 2.50.0
      disableDeltaSelector: true

  - name: Loki
    type: loki
    access: proxy
    url: http://gapanalyzer-loki:3100
    editable: false
    jsonData:
      maxLines: 1000
